### ISSUE TITLE
Custom Attribute

### ISSUE THREAD

**Issue by the-red** [kintone-labs/kintone-ui-component#518]
## Component

All

## Why

Japaneseですが、こちらに書いたようなことを簡単にできるようにしたいからです！
ご一読ください～。

kintone UI Component v1で作った要素にsetAttributeする
https://qiita.com/the_red/items/5948c597ed5d043da42a

## What

Custom attributes can be freely set.

```js
new Text({ value: '2021-04-20', attribute: { type: 'date' } })
```

**Comment by TomokoMiyake** [comment]
@the-red 
Custom Attribute についてリクエストをありがとうございます。
Qiita 記事も大変参考になります。

> でも「ラベルのattribute」とか「途中のdivのattribute」とか
> 言い出すと切りがないから難しいかなぁ。。。

最後にコメントしてくださっているように、各 HTML tag の Attribute 使えるように考慮するとなると確かにキリがない印象ではあります。
検討させてください。

[EN]
Thank you for the request about Custom Attribute.
The Qiita article is also very useful for us.

> But there's no point to carry on "attribute for label", "attribute for div in the middle of the HTML structure", and so on,
> so it might be difficult to correspond.

As you mentioned at the end of the article, when considering the use of the Attribute of each HTML tag,
it seems there is no end to it.
Let us consider it.

**Comment by TomokoMiyake** [comment]
@the-red 
ご提案いただいた Custom Attribute について検討しました。

各コンポーネントは複数階層の HTML タグで構成されているので、
それぞれの要素に対してカスタムで自由に Attribute 付与できるようにサポートするのが現状難しいです。
アレンジしたいという要望が多い部分については、プロパティでの機能追加をしていければと思っております。
引き続きご意見いただけると幸いです。

[EN]
We considered the Custom Attribute you proposed.

Since each component consists of multiple levels of HTML tags, it is currently difficult to support the ability to freely assign Custom Attributes to each element.
For the part where there are many requests to arrange, we would like to add a feature as a `property`.
We would appreciate it if you continue to give us your opinions!

**Comment by the-red** [comment]
@TomokoMiyake 
なるほどー、残念ですが了解しました。

今回は「Textフィールドで日付入力をしたい」という目的だったので、
UI Component側で、日付入力・日時入力タイプのフィールドなど
今後増やしていただけるとありがたいです！
よろしくお願いします。

**Comment by TomokoMiyake** [comment]
@the-red 
ご確認ありがとうございます。
現在 Date 系のコンポーネントも検討開始しているので、将来的にはそちらで解決いただけそうです。
引き続きよろしくお願いします。

[EN]
Thank you for checking.
Now we are considering the Date related component, so it will be the solution in the future.
